@baseUrl = http://localhost:3000

### 
GET {{baseUrl}}/contacts

###

GET {{baseUrl}}/contacts/6a57e32663045c825358e01a

###

POST {{baseUrl}}/contacts/
Content-Type: application/json

{
  "firstName": "John1",
  "lastName": "Doe1",
  "email": "john.doe1@example.com",
  "favoriteColor": "Blue1",
  "birthday": "1995-05-15"
}

###

PUT {{baseUrl}}/contacts/6a57e32663045c825358e01a
Content-Type: application/json

{
  "firstName": "John2",
  "lastName": "Watson2",
  "email": "emily1.w@example.com",
  "favoriteColor": "purple",
  "birthday": "1998-03-30"
}

###

DELETE {{baseUrl}}/contacts/6a57e32663045c825358e01a