@baseUrl = http://localhost:3000

### 
GET {{baseUrl}}/contacts

###

GET {{baseUrl}}/contacts/6a527ee43a37c617074f68a9

###

POST {{baseUrl}}/contacts/
Content-Type: application/json

{
  "firstName": "John1",
  "lastName": "Doe1",
  "email": "john.doe1@example.com",
  "favoriteColor": "Blue1",
  "birthday": "1995-05-15"
}

###

PUT {{baseUrl}}/contacts/6a527ee43a37c617074f68a9
Content-Type: application/json

{
   "lastName": "Watson2",
  "email": "emily1.w@example.com",
  "favoriteColor": "purple",
  "birthday": "1998-03-30"
}

###

DELETE {{baseUrl}}/contacts/6a4e9d6f5d2f56c44e810b32